# -*- coding: utf-8 -*-
"""model_pipeline.joblib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhMvl9wK1z5AWQo8GMVb_PBpMedaIZqA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle
import warnings
warnings.filterwarnings('ignore')

#Loading data
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)

df.head()

df.shape

df.info()

"""### **Removing Unnecessarry Values In Column**"""

df = df.drop(['customerID'],axis=1)
df.head()

"""### Exploring Unique Values in Categorical Columns"""

features = ['tenure','MontlyCharges','TotalCharges']

for col in df.columns:
  if col not in features:
    print(col,df[col].unique())
    print("-"*50)

df.isnull().sum()

df['TotalCharges'].values

df[df['TotalCharges']==" "]

len(df[df['TotalCharges']==" "])

df['TotalCharges'] = df['TotalCharges'].replace({" ":"0.0"})

df['TotalCharges'] = df['TotalCharges'].astype(float)
df.info()

df['Churn'].value_counts().plot(kind='barh',color='blue')
plt.xlabel("Count")
plt.ylabel("Churn")

df.describe()

def kdeplot(feature):
  plt.figure(figsize=(9,4))
  plt.title(f"KDE for {feature}")

  ax0 = sns.kdeplot(df[df['Churn']=="No"][feature].dropna(),color='red',label="Churn:No",shade=True)
  ax1 = sns.kdeplot(df[df['Churn']=="Yes"][feature].dropna(),color='blue',label="Churn:Yes",shade=True)

  plt.legend()
  plt.show()

kdeplot('tenure')
kdeplot('MonthlyCharges')
kdeplot('TotalCharges')

plt.figure(figsize=(8,5))
sns.countplot(x='Contract',hue='Churn',data=df,palette=['red','blue'])
plt.title("Churn by Contract Type")
plt.show()
#

plt.figure(figsize=(8,5))
sns.boxplot(x='Churn',y='MonthlyCharges',data=df,palette=['red','blue'])
plt.title("Churn by Monthly Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='InternetService',hue='Churn',data=df,palette=['red','blue'])
plt.title("Churn by InternetService")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='PaymentMethod',hue='Churn',data=df,palette=['red','blue'])
plt.xticks(rotation=45)
plt.title("Churn by PaymentMethod")
plt.show()

plt.figure(figsize=(8,4))
sns.heatmap(df[['tenure','MonthlyCharges','TotalCharges']].corr(),annot=True,cmap='coolwarm',fmt=',')
plt.title("Correlation Heatmap")
plt.show()

df.head(2)

# Replacing "No phone Service" and "No internet service" with NO
df['OnlineBackup'].replace({'No internet service':'No'},inplace=True)
df['DeviceProtection'].replace({'No internet service':'No'},inplace=True)
df['TechSupport'].replace({'No internet service':'No'},inplace=True)
df['StreamingTV'] .replace({'No internet service':'No'},inplace=True)
df['StreamingMovies'].replace({'No internet service':'No'},inplace=True)
df['MultipleLines'].replace({'No phone service':'No'},inplace=True)
df['OnlineSecurity'].replace({'No internet service':'No'},inplace=True)

yes_no_cols=['Partner','Dependents','PhoneService','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn','OnlineSecurity','MultipleLines']

for col in yes_no_cols:
  df[col].replace({'Yes':1,'No':0},inplace=True)

df.head(2)

df['gender'].replace({'Female':1,'Male':0},inplace=True)
df.head(2)

df2 = pd.get_dummies(data=df,columns=['InternetService','Contract','PaymentMethod'],dtype=int)
df2.head(5)

df2.info()

cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])
#

#Check values
for col in df2:
  print(f"{col}:{df2[col].unique()}")

#splitting the features and target
X = df2.drop(columns=['Churn'])
y = df2['Churn']

#splitting training and test
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print(y_train.value_counts())

#Creating SMOTE
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train,y_train)

print(y_train_smote.value_counts())

log_reg_model = LogisticRegression(random_state=42, solver='liblinear')
log_reg_model.fit(X_train_smote, y_train_smote)

# Make predictions on the test set
y_pred_lr = log_reg_model.predict(X_test)

# Evaluate the model
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Accuracy of Logistic Regression: {accuracy_lr}")

print("\nClassification Report for Logistic Regression:")
print(classification_report(y_test, y_pred_lr))

# Calculate ROC AUC score
roc_auc_lr = roc_auc_score(y_test, y_pred_lr)
print(f"ROC AUC Score for Logistic Regression: {roc_auc_lr}")

import joblib

#Save artifact
joblib.dump(log_reg_model, 'model_pipeline.joblib')
print("Model pipeline saved as 'model_pipeline.joblib'")

from google.colab import files

files.download('model_pipeline.joblib')